# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created. Also, will deploy the API with Vercel

name: CI/CD with Vercel

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code   # Checkout del c贸digo
        uses: actions/checkout@v2

      - name: Setup Node.js   # Configuraci贸n de node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install dependencies   # Instalaci贸n de dependencias
        run: npm install

      - name: Run tests     # Ejecuci贸n de pruebas
        run: npm test

      - name: Deploy to Vercel    # Despliegue en vercel utilizando el token de desplegamiento almacenado en los secretos del repositorio
        run: npx vercel --prod
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}  # Define this secret in your repository settings
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}  # Organization ID
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}  # Project ID
